name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_NODE_VERSION: 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_42800397
          password: HDolQvO6QbH3k
          port: 21
          protocol: ftp
          security: loose
          server-dir: ./htdocs/
          exclude: |
            **/.git**
            **/.github**
            **/.git*/**
